### PR TITLE
Implement typed maps

### PR DESCRIPTION
**Pull request by pjedge**
This PR implements typed maps in martian-rust. In other words, HashMaps that you use in the inputs and outputs of stages, will no longer be `map` in the generated MRO, they will be `map<type>`. This allows martian to do better static analysis of the Cellranger pipeline, and also enables Rust stages to pass around HashMaps holding MartianFileTypes with Martian properly tracking the files within (previously it was basically required to workaround this e.g. by passing around a Vector of key-value pairs for example.)

The main drawback of this implementation is that HashMaps are now required to have keys that implement `Hash + Display + Eq` and values that implement `MartianPrimaryType`. This is the case for most of the uses of HashMaps in the Cellranger pipeline, AFAIK there were just two cases where this was not true. For cases where your HashMap doesn't meet those bounds, it is required to use `#[mro_type = "map"]` to force the map to be untyped. AFAIK this drawback will continue to be the case until Specialization is in stable Rust, allowing there to be one implementation of `MartianBlanketType` for any HashMaps meeting the trait bounds and another for ones that do not.

### CODE REVIEW

File: martian/src/mro.rs [hunk 1]
```diff
@@ -199,6 +202,16 @@ impl MroDisplay for MartianBlanketType {
...
             MartianBlanketType::Array(ref primary) => format!("{}[]", primary.to_string()),
+            MartianBlanketType::TypedMap(ref primary) => {
+                // map of maps not allowed in Martian
+                // this is a little hacky, we allow TypedMap<map> to be passed around internally in Martian-rust
+                // but we just print it as "map"
+                if primary.to_string() == "map".to_string() {
+                    "map".to_string()
+                } else {
+                    format!("map<{}>", primary.to_string())
+                }
```
Comment (nlhepler) [inline martian/src/mro.rs:213]: should this be:
```suggestion
                match primary {
                    MartianPrimaryType::Map => "map".to_string(),
                    _ => format!("map<{}>", primary.to_string()),
                }
```

Comment (pjedge) [reply martian/src/mro.rs:213]: good catch. This was a late fix and I wasn't paying attention to the original type

**Comment by pjedge** [comment]
Remaining issues: Currently if you try to use a `HashMap` or `TxHashMap` that doesn't meet the proper trait bounds of `Display + Hash + Eq` on the key and `MartianPrimaryType` on the value, you just get a cryptic error that the HashMap doesn't implement `MartianBlanketType`. I want to figure out how to get a nice error for those bounds that also suggests that the user can use `#[mro_type = "map"]` for maps that don't meet those bounds.

File: martian-derive/tests/mro/test_typed_map.mro [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+# WARNING: This file is auto-generated.
+# DO NOT MODIFY THIS FILE DIRECTLY
+#
+
+filetype fastq;
+
+struct ReadsStruct(
+    string     name,
+    map<fastq> reads_map,
+    map[]      multi_reads_map,
```
Comment (adam-azarchs) [inline martian-derive/tests/mro/test_typed_map.mro:13]: This isn't correct.  It should be
```suggestion
    map<fastq>[]      multi_reads_map,
```
You should also add a test case for `map<fastq[]>` and maybe some multi-dimensional array types.

**Review by adam-azarchs — COMMENTED** [review]
I don't understand why this changes the requirements for map keys.  json dictionary keys were already required to be strings, so any map that can be serialized to json should already be meeting the criteria.

File: martian-derive/tests/mro/test_typed_map.mro (hunk 2 above)
Comment (pjedge) [reply martian-derive/tests/mro/test_typed_map.mro:13]: Yeah I haven't yet figured out a good way to handle arrays of typed maps. Currently it prints them as untyped. The reason is that it sort of breaks the hierarchy of types MartianRust assumes: 
```
pub enum MartianBlanketType {
    Primary(MartianPrimaryType),
    Array(MartianPrimaryType),
    TypedMap(MartianPrimaryType),
}
```
An untyped map is a primary type so you can have an array of them, but you can't have an array of a TypedMap since that's a blanket type. Perhaps the best solution would be to make ArrayOfTypedMap(MartianPrimaryType) its own blanket type here.

Martian-Rust doesn't support multidimensional arrays at the moment, although it would probably be easy to similarly add a TwoDimensionalArray(MartianPrimaryType) which serializes to and from `Vec<Vec<T>>`. `map<fastq[]>` would similarly need its own blanket type probably. @nlhepler I can't think of any other solutions, does this seem reasonable to you?

Comment (adam-azarchs) [reply martian-derive/tests/mro/test_typed_map.mro:13]: I'm not familiar enough with rust's type system but is type recursion not allowed, e.g. can you not have `Array(MartianBlanketType)`?

Comment (adam-azarchs) [reply martian-derive/tests/mro/test_typed_map.mro:13]: A quick google search suggests you could have e.g. `Array(Box<MartianBlanketType>)`.

Comment (pjedge) [reply martian-derive/tests/mro/test_typed_map.mro:13]: Regarding the trait bounds on the key, you're totally correct -- I was able to remove those bounds. I think these bounds may have been required a few commits back when my less-clean solution involved wrapping the HashMap type.

Comment (pjedge) [reply martian-derive/tests/mro/test_typed_map.mro:13]: Ohh. I think you're right

Comment (pjedge) [reply martian-derive/tests/mro/test_typed_map.mro:13]: Worked like a charm! Awesome.

Comment (adam-azarchs) [reply martian-derive/tests/mro/test_typed_map.mro]: Nice.  One thing I don't see in the test cases, however, is `map<StructType>`.  I assume that should work fine, since `StructType[]` works.

Comment (adam-azarchs) [reply martian-derive/tests/mro/test_typed_map.mro]: Also, might want to double-check that the `Box` is actually necessary.  If it works on its own or with `Option<T>` that might be better; the examples I've seen where `Box<T>` was used were cases where an enum contains a direct recursive link, whereas an array or map might be fine.

Comment (pjedge) [reply martian-derive/tests/mro/test_typed_map.mro]: Unless I'm mistaken this is a direct recursive link. There's no actual array or map contained in this type, it's just a martian type definition, and basically removing the box makes it have infinite size since it wants to statically store a full MartianBlanketType inside, and each of those contains a MartainBlanketType, and there's the overhead of the struct itself so the size blows up.
```
error[E0072]: recursive type `mro::MartianBlanketType` has infinite size
   --> martian/src/mro.rs:183:1
    |
183 | pub enum MartianBlanketType {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ recursive type has infinite size
184 |     Primary(MartianPrimaryType),
185 |     Array(MartianBlanketType),
    |           ------------------ recursive without indirection
186 |     TypedMap(MartianBlanketType),
    |              ------------------ recursive without indirection
    |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `mro::MartianBlanketType` representable
    |
185 |     Array(Box<MartianBlanketType>),
186 |     TypedMap(Box<MartianBlanketType>),
    |

error[E0391]: cycle detected when computing drop-check constraints for `mro::MartianBlanketType`
   --> martian/src/mro.rs:183:1
    |
183 | pub enum MartianBlanketType {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: ...which again requires computing drop-check constraints for `mro::MartianBlanketType`, completing the cycle
    = note: cycle used when type-checking all item bodies
```

Comment (adam-azarchs) [reply martian-derive/tests/mro/test_typed_map.mro]: Ah, yes.  It would be possible to contain `Vec<MartianBlanketType>` (since a vector is actually [size plus] a pointer to an array) but I guess that's not actually what you want in this case.

**Review by adam-azarchs — APPROVED** [review]
I'd wait for @nlhepler to comment on the rust side of this but the martian side LGTM.

File: martian/src/mro.rs [hunk 3]
```diff
@@ -284,24 +320,26 @@ impl<T: AsMartianBlanketType> AsMartianBlanketType for Option<T> {
...
-    fn as_martian_primary_type() -> MartianPrimaryType {
-        MartianPrimaryType::Map
+// ideally we'd allow for any HashMap to be turned into a typed Map when possible, or an untyped Map by default
+// but a typed map can only be made for Rust HashMap with a key implementing Display + Eq + Hash
+// and a value implementing MartianPrimaryType
+// it is not possible to have multiple implementations ranked in priority without specialization, which is an unstable feature
+// and it is impossible to check what traits are implemented for a HashMap's K,V at runtime.
+// instead, the current solution is that any HashMap not meeting these trait bounds must manually specify the type
+// using #[mro_type = "map"]
+impl<K, V: AsMartianBlanketType, H> AsMartianBlanketType for HashMap<K, V, H> {
```
Comment (sreenathkrishnan) [inline martian/src/mro.rs:340]: I would keep `HashMap` as an untyped generic map with no restrictions and define a struct `TypedMap<K, V, H>` which is a simple wrapper around `HashMap<K, V, H>` where `V: AsMartianBlanketType`. This preserves backward compatibility but also makes typed map an opt in. What do you think about that?

File: martian/src/mro.rs [hunk 4]
```diff
@@ -181,14 +182,16 @@ mro_display_to_display! {MartianPrimaryType}
 #[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, Hash)]
 pub enum MartianBlanketType {
     Primary(MartianPrimaryType),
-    Array(MartianPrimaryType),
+    Array(Box<MartianBlanketType>),
+    TypedMap(Box<MartianBlanketType>),
```
Comment (sreenathkrishnan) [inline martian/src/mro.rs:186]: Can `TypedMap` be a `MartianPrimaryType`?

File: martian/src/mro.rs (hunk 3 above)
Comment (pjedge) [reply martian/src/mro.rs:340]: Hmmm. I tried this strategy earlier but found it not very ergonomic to implement. The least annoying way would involve having TypedMap implement `Deref` and `DerefMut` so that it can effectively "inherit" the functionality of the contained map without having to unwrap it or implement a suite of accessors. But I think I ran into some trouble doing this because of the HashMap's generic type parameters. Further, it would become necessary to pass around the Hasher we need unless we decide to abstract them away as with `TxHashMap`. Would you recommend we also create a `TypedTxHashMap` newtype in `metric` and make `Martian` a new dependency of `metric`?

Comment (pjedge) [reply martian/src/mro.rs:340]: Personally, I was of the same mind as you, but the fact that I only had to manually untype 2 or 3 Maps in the entire Cellranger pipeline implies this isn't the worst breaking change we could have. And I think @adam-azarchs was pushing earlier for typed maps by default.

File: martian/src/mro.rs (hunk 4 above)
Comment (pjedge) [reply martian/src/mro.rs:186]: Hmmm what would be the benefit of that over this design?

Comment (pjedge) [reply martian/src/mro.rs:186]: Even if it were a `MartianPrimaryType` TypedMap would still need to contain `Box<MartianBlanketType>` if we want it to be able to contain `Array`s.

File: martian/src/mro.rs (hunk 3 above)
Comment (sreenathkrishnan) [reply martian/src/mro.rs:340]: Ah, if it's just 2 or 3 untyped maps in all of cellranger, that's not bad.

Comment (adam-azarchs) [reply martian/src/mro.rs:340]: Best practices should always be on by default.  Untyped map should be opt-in and strongly discoraged.

File: martian/src/mro.rs (hunk 4 above)
Comment (pjedge) [reply martian/src/mro.rs:186]: `map<type[]>` is allowed, as is `map<type[][]>`, `map<type>[]`, `map<type>[][]`, etc. `map<map<_>>` is the only thing that isn't allowed. We catch that in this framework in a sort-of hacky way by checking for that at `mro` printing time, and forcing it to just terminate the recursion by printing `map` instead of `map<map<...>>`

File: martian/src/mro.rs (hunk 3 above)
Comment (adam-azarchs) [reply martian/src/mro.rs:340]: Really the only case where an untyped map should ever be produced is where martian doesn't allow one to express the type constraint, e.g. where the values are an `enum` type.  Though in most such cases what you should probably actually have is a `struct`.

File: martian-derive/tests/mro/test_empty_split.mro [hunk 5]
```diff
@@ -6,10 +6,10 @@
...
 
 stage CHUNK_READS(
-    in  map[] chunks,
-    in  int   reads_per_file,
-    out map[] out_chunks,
-    src comp  "my_adapter martian chunker",
+    in  map<int>[] chunks,
+    in  int        reads_per_file,
+    out map<int>[] out_chunks,
+    src comp       "my_adapter martian chunker",
```
Comment (adam-azarchs) [inline martian-derive/tests/mro/test_empty_split.mro:12]: Side note: perhaps it would be a good idea to include a test that the output mro is unchanged by `mro format`.  This could be a separate CI test action, just downloading the [martian release tarball](https://github.com/martian-lang/martian/releases/download/v4.0.3/martian-v4.0.3-linux-x86_64.tar.xz) to get the tool and verifying these files.

**Review by sreenathkrishnan — APPROVED** [review]
Makes sense! Thank you for getting this through :)

**Review by nlhepler — APPROVED** [review]
LGTM! :+1:
